### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by samwhu30** [taurgis/homebridge-iRobot-v2#14]
### Describe The Bug:

I updated my Homebridge and after restarting I'm now getting errors and the plug in wont load. It initially stopped the whole of my homebridge to stop working until I put it into a child bridge.

### To Reproduce:

I updated Homebridge (UI I think?) and now the plugin wont run.

### Expected behavior:

Plug in should launch

### Logs:

```shell
[10/14/2024, 12:18:10 PM] Registering platform 'homebridge-irobot-v2.iRobotPlatform'
[10/14/2024, 12:18:11 PM] [iRobot] Loaded homebridge-irobot-v2 v3.2.1 child bridge successfully
[10/14/2024, 12:18:11 PM] [iRobot] Logging into iRobot...
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
[10/14/2024, 12:18:11 PM] Homebridge v1.8.4 (HAP v0.12.2) (iRobot) is running on port 33009.
[10/14/2024, 12:18:11 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94
            loginIrobotResponseHandler(null, res, JSON.parse(data));
                                                       ^
Error: Command failed: /homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js post_02frazzle@icloud.com jEdfup-qixvy2-qyczug
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at Object.execFileSync (node:child_process:927:15)
    at getRoombas (/homebridge/node_modules/homebridge-irobot-v2/src/getRoombas.ts:13:38)
    at iRobotPlatform.discoverDevices (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:55:35)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:30:18)
    at HomebridgeAPI.emit (node:events:519:28)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:194:14)
[10/14/2024, 12:18:11 PM] [iRobot] Child bridge process ended
[10/14/2024, 12:18:11 PM] [iRobot] Process Ended. Code: 1, Signal: null
[10/14/2024, 12:18:18 PM] [iRobot] Restarting Process...
[10/14/2024, 12:18:19 PM] [iRobot] Launched child bridge with PID 33725
[10/14/2024, 12:18:19 PM] Registering platform 'homebridge-irobot-v2.iRobotPlatform'
[10/14/2024, 12:18:20 PM] [iRobot] Loaded homebridge-irobot-v2 v3.2.1 child bridge successfully
[10/14/2024, 12:18:20 PM] [iRobot] Logging into iRobot...
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
[10/14/2024, 12:18:20 PM] Homebridge v1.8.4 (HAP v0.12.2) (iRobot) is running on port 33009.
[10/14/2024, 12:18:20 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94
            loginIrobotResponseHandler(null, res, JSON.parse(data));
                                                       ^
Error: Command failed: /homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js post_02frazzle@icloud.com jEdfup-qixvy2-qyczug
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at Object.execFileSync (node:child_process:927:15)
    at getRoombas (/homebridge/node_modules/homebridge-irobot-v2/src/getRoombas.ts:13:38)
    at iRobotPlatform.discoverDevices (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:55:35)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:30:18)
    at HomebridgeAPI.emit (node:events:519:28)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:194:14)
[10/14/2024, 12:18:20 PM] [iRobot] Child bridge process ended
[10/14/2024, 12:18:20 PM] [iRobot] Process Ended. Code: 1, Signal: null
[10/14/2024, 12:18:27 PM] [iRobot] Restarting Process...
[10/14/2024, 12:18:28 PM] [iRobot] Launched child bridge with PID 33755
[10/14/2024, 12:18:28 PM] Registering platform 'homebridge-irobot-v2.iRobotPlatform'
[10/14/2024, 12:18:29 PM] [iRobot] Loaded homebridge-irobot-v2 v3.2.1 child bridge successfully
[10/14/2024, 12:18:29 PM] [iRobot] Logging into iRobot...
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
[10/14/2024, 12:18:29 PM] Homebridge v1.8.4 (HAP v0.12.2) (iRobot) is running on port 33009.
[10/14/2024, 12:18:29 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94
            loginIrobotResponseHandler(null, res, JSON.parse(data));
                                                       ^
Error: Command failed: /homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js post_02frazzle@icloud.com jEdfup-qixvy2-qyczug
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at Object.execFileSync (node:child_process:927:15)
    at getRoombas (/homebridge/node_modules/homebridge-irobot-v2/src/getRoombas.ts:13:38)
    at iRobotPlatform.discoverDevices (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:55:35)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:30:18)
    at HomebridgeAPI.emit (node:events:519:28)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:194:14)
[10/14/2024, 12:18:29 PM] [iRobot] Child bridge process ended
[10/14/2024, 12:18:29 PM] [iRobot] Process Ended. Code: 1, Signal: null
[10/14/2024, 12:18:36 PM] [iRobot] Restarting Process...
[10/14/2024, 12:18:37 PM] [iRobot] Launched child bridge with PID 33789
[10/14/2024, 12:18:37 PM] Registering platform 'homebridge-irobot-v2.iRobotPlatform'
[10/14/2024, 12:18:37 PM] [iRobot] Loaded homebridge-irobot-v2 v3.2.1 child bridge successfully
[10/14/2024, 12:18:37 PM] [iRobot] Logging into iRobot...
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
[10/14/2024, 12:18:38 PM] Homebridge v1.8.4 (HAP v0.12.2) (iRobot) is running on port 33009.
[10/14/2024, 12:18:38 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94
            loginIrobotResponseHandler(null, res, JSON.parse(data));
                                                       ^
Error: Command failed: /homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js post_02frazzle@icloud.com jEdfup-qixvy2-qyczug
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at Object.execFileSync (node:child_process:927:15)
    at getRoombas (/homebridge/node_modules/homebridge-irobot-v2/src/getRoombas.ts:13:38)
    at iRobotPlatform.discoverDevices (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:55:35)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:30:18)
    at HomebridgeAPI.emit (node:events:519:28)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:194:14)
[10/14/2024, 12:18:38 PM] [iRobot] Child bridge process ended
[10/14/2024, 12:18:38 PM] [iRobot] Process Ended. Code: 1, Signal: null
[10/14/2024, 12:18:45 PM] [iRobot] Restarting Process...
[10/14/2024, 12:18:46 PM] [iRobot] Launched child bridge with PID 33816
[10/14/2024, 12:18:46 PM] Registering platform 'homebridge-irobot-v2.iRobotPlatform'
[10/14/2024, 12:18:46 PM] [iRobot] Loaded homebridge-irobot-v2 v3.2.1 child bridge successfully
[10/14/2024, 12:18:46 PM] [iRobot] Logging into iRobot...
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
[10/14/2024, 12:18:47 PM] Homebridge v1.8.4 (HAP v0.12.2) (iRobot) is running on port 33009.
[10/14/2024, 12:18:47 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94
            loginIrobotResponseHandler(null, res, JSON.parse(data));
                                                       ^
Error: Command failed: /homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js post_02frazzle@icloud.com jEdfup-qixvy2-qyczug
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at Object.execFileSync (node:child_process:927:15)
    at getRoombas (/homebridge/node_modules/homebridge-irobot-v2/src/getRoombas.ts:13:38)
    at iRobotPlatform.discoverDevices (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:55:35)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:30:18)
    at HomebridgeAPI.emit (node:events:519:28)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:194:14)
[10/14/2024, 12:18:47 PM] [iRobot] Child bridge process ended
[10/14/2024, 12:18:47 PM] [iRobot] Process Ended. Code: 1, Signal: null
[10/14/2024, 12:18:54 PM] [iRobot] Restarting Process...
[10/14/2024, 12:18:55 PM] [iRobot] Launched child bridge with PID 33846
[10/14/2024, 12:18:55 PM] Registering platform 'homebridge-irobot-v2.iRobotPlatform'
[10/14/2024, 12:18:55 PM] [iRobot] Loaded homebridge-irobot-v2 v3.2.1 child bridge successfully
[10/14/2024, 12:18:55 PM] [iRobot] Logging into iRobot...
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
[10/14/2024, 12:18:56 PM] Homebridge v1.8.4 (HAP v0.12.2) (iRobot) is running on port 33009.
[10/14/2024, 12:18:56 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94
            loginIrobotResponseHandler(null, res, JSON.parse(data));
                                                       ^
Error: Command failed: /homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js post_02frazzle@icloud.com jEdfup-qixvy2-qyczug
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/dist/scripts/getRoombaCredentials.js:94:56)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v20.18.0
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at Object.execFileSync (node:child_process:927:15)
    at getRoombas (/homebridge/node_modules/homebridge-irobot-v2/src/getRoombas.ts:13:38)
    at iRobotPlatform.discoverDevices (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:55:35)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-irobot-v2/src/platform.ts:30:18)
    at HomebridgeAPI.emit (node:events:519:28)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:194:14)
[10/14/2024, 12:18:56 PM] [iRobot] Child bridge process ended
[10/14/2024, 12:18:56 PM] [iRobot] Process Ended. Code: 1, Signal: null
```

### Config:

```shell
{
    "name": "iRobot",
    "email": "############",
    "password": "###########",
    "roombas": [
        {
            "autoConfig": true,
            "info": {
                "ver": 2
            }
        }
    ],
    "manualDiscovery": false,
    "lowBattery": 20,
    "offAction": "stop:dock",
    "status": "cycle:clean",
    "eveStatus": "inverted:cycle:clean",
    "bin": "none",
    "ignoreMultiRoomBin": true,
    "hideStuckSensor": false,
    "disableMultiRoom": false,
    "_bridge": {
        "username": "########",
        "port": #####
    },
    "platform": "iRobotPlatform"
}
```

### Node Version:

v20.18.0

### NPM Version:

couldnt find?

### Homebridge Version:

v1.8.4

### Plugin Version:

v3.2.1

### Operating System:

Docker

**Comment by taurgis** [comment]
This looks like the login API returning an HTML rather than a regular response. Have you verified your credentials to be correct?

However, I did commit with an extra catch, not to crash the environment.

**Comment by taurgis** [comment]
I just restarted my Homebridge and have the same error.

**Comment by samwhu30** [comment]
> This looks like the login API returning an HTML rather than a regular response. Have you verified your credentials to be correct?
> 
> However, I did commit with an extra catch, not to crash the environment.

I just logged out and back in to check the credentials are correct

**Comment by taurgis** [comment]
I looked at the error and seems something is broken on the iRobot side (hopefully only today)

`    CloudFront wasn't able to resolve the origin domain name.
    We can't connect to the server for this app or website at this time. There might be too much traffic or a
    configuration error. Try again later, or contact the app or website owner.`

I will monitor, hopefully this will fix itself. Otherwise this is going to be a tricky one...

**Comment by taurgis** [comment]
> > This looks like the login API returning an HTML rather than a regular response. Have you verified your credentials to be correct?
> > However, I did commit with an extra catch, not to crash the environment.
> 
> I just logged out and back in to check the credentials are correct

I just pushed a new version that at least doesn't crash the entire instance.

**Comment by taurgis** [comment]
I just pushed an alpha version that connects to the auth01 URL rather than auth02. This resolves the issue.

**Comment by samwhu30** [comment]
Wow that was quick! All fixed now, thank you 😊

**Comment by taurgis** [comment]
> Wow that was quick! All fixed now, thank you 😊

No problem! I will monitor the old URL in the coming days and possibly build a fallback system between both URLs. But that is for the next alpha version when I have more time.
